title = "Travel around the world"
baseURL = "https://exmo.travel"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
resourceDir = "../resources"

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
#Paginate = 12 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
[pagination]
  pagerSize = 12

[languages]
  [languages.de]
    title = "exmo.travel"
    weight = 1
    contentDir = "content/de"
    languageName = "🇩🇪"
    languageCode = "de-DE"
  [languages.en]
    title = "exmo.travel"
    weight = 2
    contentDir = "content/en"
    languageName = "🇬🇧"
    languageCode = "en-us"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Sven Walther"
  favicon = "/favicon.png"
  site_logo = "/images/exmo.travel-logo-white.png"
  description = "Travelling around the world"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  recent_posts_number = 12
  mainSections = ["post"]
  body_classes = "aller bg-solarized-light"
  background_color_class = "bg-solarized-light"
  footer_background_color_class = "bg-solarized-dark"

[params.ananke.social.follow]
networks = [
  "youtube",
  "instagram",
  "mastodon",
  "facebook"
]

[params.ananke.social.facebook]
  username = "exmo.travel"
  profilelink = "https://www.facebook.com/people/Exmotravel/61563591726442/"

[params.ananke.social.youtube]
  name = "youtube"
  username = "exmo-travel"
  #url = "https://www.youtube.com/@exmo-travel"

[params.ananke.social.instagram]
  username = "exmo.travel"

[params.ananke.social.mastodon]
  profilelink = "https://mastodon.cloud/@exmotravel"