title = "Travel around the world"
baseURL = "https://exmo.travel"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.de]
    title = "exmo.travel"
    weight = 1
    contentDir = "content/de"
    languageName = "🇩🇪"
  [languages.en]
    title = "exmo.travel"
    weight = 2
    contentDir = "content/en"
    languageName = "🇬🇧"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Sven Walther"
  favicon = "/favicon.png"
  site_logo = "/images/exmo.travel-logo-white.png"
  description = "Travelling around the world"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 3

[[params.ananke_socials]]
  name = "youtube"
  url = "https://www.youtube.com/@exmo-travel"
[[params.ananke_socials]]
  name = "instagram"
  url = "https://www.instagram.com/exmo.travel/"
[[params.ananke_socials]]
  name = "mastodon"
  url = "https://mastodon.cloud/@exmotravel"
[[params.ananke_socials]]
  name = "facebook"
  url = "https://www.facebook.com/people/Exmotravel/61563591726442/"
